spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: dbuser
    password: admin2021
    url: jdbc:postgresql://localhost:5432/fornecedor