spring:
  datasource:
    username: authentication
    password: authentication
    platform: postgres
    initialization-mode: always
    url: jdbc:postgresql://docker-postgres:5432/authentication
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
