spring:
  datasource:
    username: dbuser
    password: admin2021
    platform: postgres
    initialization-mode: always
    url: jdbc:postgresql://pgadmin.afcoding.com.br:5432/authentication
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
